"""substantial change

Revision ID: bc362f9981ac
Revises: ecb1037ab271
Create Date: 2024-04-12 16:24:20.478586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc362f9981ac'
down_revision = 'ecb1037ab271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uploadtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('asset_name'),
    sa.UniqueConstraint('asset_path')
    )
    op.drop_table('filedata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filedata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataname', sa.VARCHAR(), nullable=False),
    sa.Column('datapath', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('uploadtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataname'),
    sa.UniqueConstraint('datapath')
    )
    op.drop_table('assets')
    # ### end Alembic commands ###
