"""changed

Revision ID: cd6ba5a807a2
Revises: 93bffcc70e36
Create Date: 2024-02-25 11:17:59.707996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6ba5a807a2'
down_revision = '93bffcc70e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataname', sa.String(), nullable=False),
    sa.Column('datapath', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataname'),
    sa.UniqueConstraint('datapath')
    )
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('filedata')
    # ### end Alembic commands ###
