"""column updated

Revision ID: ecb1037ab271
Revises: cd6ba5a807a2
Create Date: 2024-03-26 11:13:47.538078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb1037ab271'
down_revision = 'cd6ba5a807a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filedata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploadtime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filedata', schema=None) as batch_op:
        batch_op.drop_column('uploadtime')

    # ### end Alembic commands ###
